import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import LinearSVC
from textblob import TextBlob

# Existing abstracts and their corresponding categories
abstracts = [
    # Experimental Research
    ("This paper presents the results of an experiment on the effects of a new drug.", "Experimental Research"),
    ("A study investigating the impact of different fertilizers on crop yield.", "Experimental Research"),
    ("An experiment to assess the effectiveness of a new teaching method in improving student performance.", "Experimental Research"),
    ("This paper presents the results of an experiment on the effects of a new drug.", "Experimental Research"),
    ("A study investigating the impact of different fertilizers on crop yield.", "Experimental Research"),
    ("An experiment to assess the effectiveness of a new teaching method in improving student performance.", "Experimental Research"),
    ("An experimental study on the mechanical properties of carbon nanotubes.", "Experimental Research"),
    ("A randomized controlled trial evaluating the efficacy of a novel pain management technique.", "Experimental Research"),
    ("An experiment investigating the impact of temperature on the growth of bacteria cultures.", "Experimental Research"),
    ("A study on the effects of various exercise regimens on cardiovascular health markers.", "Experimental Research"),
    ("An experimental analysis of the impact of social media usage on self-esteem in adolescents.", "Experimental Research"),
    ("A controlled experiment to evaluate the effects of a new diet plan on weight loss.", "Experimental Research"),
    ("An investigation into the effects of music therapy on reducing anxiety in hospital patients.", "Experimental Research"),
    ("An experimental study on the efficiency of different solar panel configurations.", "Experimental Research"),
    ("A comparative study on the performance of different data compression algorithms.", "Experimental Research"),
    ("An experimental study investigating the impact of collaborative innovation platforms on idea generation and knowledge sharing within organizations.", "Experimental Research"),
    ("Examining the effects of different incentive structures on the creativity and productivity of research and development teams in innovation-driven companies.", "Experimental Research"),
    ("A controlled experiment assessing the effectiveness of a novel innovation training program on enhancing individuals' creative problem-solving abilities.", "Experimental Research"),
    ("An experimental study investigating the effects of different incentive structures on creativity and innovation performance within innovation teams.", "Experimental Research"),
    ("Examining the impact of varying levels of organizational autonomy on innovation outcomes in different types of innovation systems.", "Experimental Research"),
    ("An experiment exploring the effects of collaborative platforms and knowledge-sharing mechanisms on innovation capability and knowledge diffusion within innovation systems.", "Experimental Research"),
    ("An experimental study investigating the impact of different reward systems on employee creativity and innovation within innovation-driven organizations.", "Experimental Research"),
    ("Examining the effects of various team compositions on innovation outcomes and team performance in interdisciplinary innovation projects.", "Experimental Research"),
    ("An experiment assessing the influence of different idea generation techniques on the quantity and quality of innovative ideas within innovation teams.", "Experimental Research"),
    ("A controlled study examining the effects of physical workspace design on creativity and innovation in co-working spaces within innovation ecosystems.", "Experimental Research"),
    ("An experimental investigation of the impact of diverse team compositions on innovation performance and the generation of disruptive ideas within innovation systems.", "Experimental Research"),
    ("Examining the effects of different leadership styles on innovation climate and employee innovative behavior in organizations within innovation ecosystems.", "Experimental Research"),


    # Observational Research
    ("A cross-sectional study examining the relationship between smoking and lung cancer.", "Observational Research"),
    ("An analysis of survey data to explore the correlation between sleep patterns and mental health.", "Observational Research"),
    ("A cohort study investigating the long-term effects of a specific diet on cardiovascular health.", "Observational Research"),
    ("A cross-sectional study examining the relationship between smoking and lung cancer.", "Observational Research"),
    ("An analysis of survey data to explore the correlation between sleep patterns and mental health.", "Observational Research"),
    ("A cohort study investigating the long-term effects of a specific diet on cardiovascular health.", "Observational Research"),
    ("A population-based study on the prevalence of diabetes in a rural community.", "Observational Research"),
    ("An observational analysis of wildlife behavior in response to climate change.", "Observational Research"),
    ("A longitudinal study tracking the educational attainment and career outcomes of high school graduates.", "Observational Research"),
    ("An analysis of historical weather data to assess the impact of climate change on crop yields.", "Observational Research"),
    ("A retrospective study examining the association between medication use and adverse drug reactions.", "Observational Research"),
    ("An observational analysis of consumer behavior in online shopping platforms.", "Observational Research"),
    ("A study on the factors influencing employee job satisfaction in a multinational corporation.", "Observational Research"),
    ("An observational investigation into the effects of air pollution on respiratory health in urban areas.", "Observational Research"),
    ("A cross-cultural study on the social norms and behaviors related to gift-giving.", "Observational Research"),
    ("A longitudinal study exploring the evolution of regional innovation systems and their impact on economic growth and competitiveness over a 10-year period.", "Observational Research"),
    ("An analysis of patent data to investigate the patterns and trends in technological innovation across different industries and geographical regions.", "Observational Research"),
    ("A cross-national study examining the factors influencing the success of innovation ecosystems in fostering entrepreneurship and innovation activities.", "Observational Research"),
    ("A longitudinal study examining the evolution of innovation ecosystems and the dynamics of knowledge transfer and collaboration within innovation systems.", "Observational Research"),
    ("An analysis of innovation data to identify the key drivers and barriers to innovation within regional innovation systems.", "Observational Research"),
    ("A cross-sectional study investigating the relationship between innovation policies and the performance of innovation systems across different countries.", "Observational Research"),
    ("A longitudinal study analyzing the evolution of innovation networks and collaboration patterns within innovation systems over a 5-year period.", "Observational Research"),
    ("An analysis of patent data to identify the key technological domains and industries driving innovation within national innovation systems.", "Observational Research"),
    ("A cross-national study examining the factors influencing the success of innovation policy initiatives within different innovation systems.", "Observational Research"),
    ("Investigating the impact of government funding programs on the innovation activities and performance of small and medium-sized enterprises (SMEs) within regional innovation systems.", "Observational Research"),
    ("An observational study exploring the role of knowledge brokers in facilitating knowledge transfer and collaboration within innovation systems.", "Observational Research"),
    ("Analyzing the effects of industry-university collaborations on innovation outcomes in innovation systems.", "Observational Research"),
    ("A comparative study of innovation ecosystems in different countries to identify the factors contributing to their success and competitiveness within innovation systems.", "Observational Research"),
    ("Examining the relationship between regional innovation systems and sustainable development outcomes through an analysis of economic, social, and environmental indicators.", "Observational Research"),
    ("An observational study investigating the impact of intellectual property rights protection on innovation behavior and outcomes within innovation systems.", "Observational Research"),
    ("Analyzing the effects of knowledge spillovers on innovation performance within innovation systems through a study of inter-organizational collaborations.", "Observational Research"),
    ("A longitudinal study examining the effects of government policy changes on the innovation activities and performance of firms within national innovation systems.", "Observational Research"),
    ("Investigating the role of innovation intermediaries in facilitating knowledge exchange and collaboration within innovation systems.", "Observational Research"),


    # Review Papers
    ("A comprehensive review of literature on the role of genetics in cancer development.", "Review"),
    ("An overview of research on renewable energy sources and their potential for sustainable development.", "Review"),
    ("A systematic review and meta-analysis of studies on the efficacy of cognitive-behavioral therapy for anxiety disorders.", "Review"),
    ("A systematic review of studies on the efficacy of mindfulness-based interventions for stress reduction.", "Review"),
    ("A comprehensive review of research on the impact of air pollution on respiratory health.", "Review"),
    ("An updated review of literature on the benefits and challenges of telemedicine in healthcare delivery.", "Review"),
    ("A meta-review of meta-analyses examining the effects of exercise on cognitive function in older adults.", "Review"),
    ("A review of studies investigating the role of gut microbiota in immune system development and function.", "Review"),
    ("An overview of research on the impact of social media on mental health and well-being.", "Review"),
    ("A systematic review of randomized controlled trials on the efficacy of cognitive training for improving memory in older adults.", "Review"),
    ("A comprehensive review of literature on the effects of climate change on biodiversity.", "Review"),
    ("An updated review of studies on the effectiveness of vaccines for preventing infectious diseases.", "Review"),
    ("A systematic review and meta-analysis of interventions for reducing burnout among healthcare professionals.", "Review"),
    ("A review of research on the applications of artificial intelligence in financial forecasting and investment strategies.", "Review"),
    ("An overview of studies on the effects of dietary interventions on metabolic syndrome risk factors.", "Review"),
    ("A systematic literature review of the main theoretical frameworks and models used in innovation systems research, identifying their key components and interactions.", "Review"),
    ("An overview of research on the role of government policies in shaping national innovation systems and promoting innovation and technological development.", "Review"),
    ("A comprehensive review of studies on the impact of open innovation practices on firm performance and competitiveness in the context of innovation systems.", "Review"),
    ("A systematic review of the literature on the role of intermediaries in fostering knowledge exchange and collaboration within innovation systems.", "Review"),
    ("An overview of research on the governance mechanisms and institutional arrangements that shape the functioning of innovation systems.", "Review"),
    ("A comprehensive review of studies on the relationship between innovation systems and sustainable development.", "Review"),
    ("A comprehensive review of studies on the role of entrepreneurship in driving innovation within innovation systems.", "Review"),
    ("An overview of research on the impact of digital technologies on innovation processes within innovation systems.", "Review"),
    ("A systematic review of the literature on the role of universities in fostering innovation within regional innovation systems.", "Review"),
    ("An analysis of research on the effectiveness of innovation policies and programs in promoting sustainable development within innovation systems.", "Review"),
    ("A comprehensive review of studies on the role of social networks in facilitating knowledge exchange and collaboration within innovation systems.", "Review"),
    ("An overview of research on the influence of cultural factors on innovation dynamics within innovation systems.", "Review"),
    ("A systematic review and meta-analysis of studies on the relationship between knowledge diversity and innovation outcomes within innovation systems.", "Review"),
    ("An analysis of research on the role of intellectual property rights in shaping innovation ecosystems within national innovation systems.", "Review"),
    ("A comprehensive review of studies on the adoption and diffusion of innovation within innovation systems.", "Review"),
    ("An overview of research on the challenges and opportunities of open innovation practices within innovation systems.", "Review"),
    ("A systematic review of the literature on the role of funding mechanisms in supporting innovation activities within innovation systems.", "Review"),
    ("An analysis of research on the impact of collaboration networks on knowledge creation and innovation performance within innovation systems.", "Review"),


    # Theoretical or Conceptual Papers
    ("A theoretical framework proposing a new model for understanding social networks.", "Theoretical or Conceptual"),
    ("An exploration of the concept of self-efficacy and its implications for motivation and achievement.", "Theoretical or Conceptual"),
    ("A conceptual analysis of the ethical implications of artificial intelligence in healthcare.", "Theoretical or Conceptual"),
    ("A conceptual framework for understanding the role of emotional intelligence in leadership effectiveness.", "Theoretical or Conceptual"),
    ("An exploration of the concept of information overload and its implications for decision-making processes.", "Theoretical or Conceptual"),
    ("A theoretical model proposing the influence of personality traits on career success and satisfaction.", "Theoretical or Conceptual"),
    ("An analysis of the social construction of gender and its impact on societal norms and expectations.", "Theoretical or Conceptual"),
    ("A conceptual framework for understanding the factors influencing consumer behavior in the e-commerce industry.", "Theoretical or Conceptual"),
    ("A theoretical model of motivation and engagement in educational settings based on self-determination theory.", "Theoretical or Conceptual"),
    ("An exploration of the ethical implications of gene editing technologies and their potential impact on human society.", "Theoretical or Conceptual"),
    ("A conceptual analysis of the concept of trust in interpersonal relationships and its role in organizational contexts.", "Theoretical or Conceptual"),
    ("A theoretical framework for understanding the impact of cultural diversity on team performance and collaboration.", "Theoretical or Conceptual"),
    ("An analysis of the concept of resilience and its relevance to psychological well-being and coping mechanisms.", "Theoretical or Conceptual"),
    ("A theoretical model proposing the influence of social support on health outcomes in chronic illness management.", "Theoretical or Conceptual"),
    ("An exploration of the concept of mindfulness and its applications in promoting mental health and well-being.", "Theoretical or Conceptual"),
    ("A conceptual framework proposing a holistic approach to understanding innovation systems, integrating social, economic, and technological dimensions.", "Theoretical or Conceptual"),
    ("Exploring the concept of innovation ecosystem resilience and its implications for the adaptive capacity and sustainability of regional innovation systems.", "Theoretical or Conceptual"),
    ("A theoretical analysis of the key elements and dynamics involved in the co-evolution of technological innovation and institutional change within innovation systems.", "Theoretical or Conceptual"),
    ("A conceptual framework for understanding the dynamics of technological change and innovation diffusion within innovation systems.", "Theoretical or Conceptual"),
    ("Exploring the concept of innovation system resilience and its implications for the adaptive capacity and sustainability of innovation ecosystems.", "Theoretical or Conceptual"),
    ("A theoretical analysis of the mechanisms and processes through which knowledge spillovers occur within innovation systems.", "Theoretical or Conceptual"),
    ("A conceptual framework for understanding the role of absorptive capacity in knowledge acquisition and innovation within innovation systems.", "Theoretical or Conceptual"),
    ("Exploring the concept of technological trajectories and their implications for innovation system dynamics.", "Theoretical or Conceptual"),
    ("A theoretical analysis of the relationship between knowledge spillovers and innovation diffusion within innovation systems.", "Theoretical or Conceptual"),
    ("Developing a conceptual model for assessing the innovation capabilities of firms within innovation systems.", "Theoretical or Conceptual"),
    ("Exploring the concept of ecosystemic innovation and its implications for innovation system governance and policy-making.", "Theoretical or Conceptual"),
    ("A theoretical analysis of the role of institutions in shaping the evolution and performance of innovation systems.", "Theoretical or Conceptual"),
    ("Developing a conceptual framework for understanding the dynamics of knowledge creation and innovation networks within innovation systems.", "Theoretical or Conceptual"),
    ("Exploring the concept of technological diversity and its role in fostering innovation within innovation systems.", "Theoretical or Conceptual"),
    ("A theoretical analysis of the factors influencing the success and failure of innovation ecosystems within regional innovation systems.", "Theoretical or Conceptual"),
    ("Developing a conceptual model for understanding the co-evolution of industries and innovation systems.", "Theoretical or Conceptual"),
    ("Exploring the concept of innovation system governance and its implications for policy design and implementation.", "Theoretical or Conceptual"),
    ("A theoretical analysis of the role of knowledge brokers in facilitating knowledge transfer and collaboration within innovation systems.", "Theoretical or Conceptual"),


    # Computational or Modeling Papers
    ("Development of a machine learning algorithm for predicting stock market trends.", "Computational or Modeling"),
    ("A computational simulation of fluid dynamics in aerodynamics research.", "Computational or Modeling"),
    ("Modeling the spread of infectious diseases using agent-based simulations.", "Computational or Modeling"),
    ("Simulation of traffic flow using cellular automata models for urban planning.", "Computational or Modeling"),
    ("Development of a machine learning algorithm for predicting customer churn in a telecommunications company.", "Computational or Modeling"),
    ("Modeling the spread of misinformation on social media networks using network analysis techniques.", "Computational or Modeling"),
    ("A computational model for optimizing the allocation of healthcare resources in a regional hospital.", "Computational or Modeling"),
    ("Investigation of the impact of climate change on agricultural productivity using climate modeling and crop simulation.", "Computational or Modeling"),
    ("Development of a deep learning-based approach for automated diagnosis of skin cancer from dermoscopic images.", "Computational or Modeling"),
    ("Modeling the effects of air pollution on respiratory health outcomes using a spatiotemporal statistical model.", "Computational or Modeling"),
    ("A computational study of protein-ligand interactions for drug discovery using molecular docking simulations.", "Computational or Modeling"),
    ("Optimization of inventory management in a supply chain using a discrete event simulation approach.", "Computational or Modeling"),
    ("Development of a predictive model for stock market movements using recurrent neural networks.", "Computational or Modeling"),
    ("Modeling the dynamics of predator-prey interactions in an ecosystem using mathematical equations and simulation.", "Computational or Modeling"),
    ("A computational approach for predicting protein structure and function based on amino acid sequences.", "Computational or Modeling"),
    ("Developing an agent-based simulation model to study the emergence and evolution of innovation networks within regional innovation systems.", "Computational or Modeling"),
    ("A computational analysis of the impact of network structure and knowledge flows on the diffusion of innovation in complex innovation systems.", "Computational or Modeling"),
    ("Using a mathematical model to simulate the dynamics of technological transitions and assess the effects of policy interventions on innovation trajectories within national innovation systems.", "Computational or Modeling"),
    ("Developing an agent-based simulation model to study the emergence and evolution of innovation networks within innovation systems.", "Computational or Modeling"),
    ("A computational analysis of the impact of network structure and knowledge flows on innovation diffusion within innovation systems.", "Computational or Modeling"),
    ("Using a mathematical model to simulate the effects of policy interventions on the dynamics of innovation ecosystems within regional innovation systems.", "Computational or Modeling"),
    ("Developing a simulation model to analyze the effects of innovation policies on the emergence of regional innovation clusters within innovation systems.", "Computational or Modeling"),
    ("Using agent-based modeling to explore the impact of knowledge spillovers and network dynamics on the evolution of innovation ecosystems within innovation systems.", "Computational or Modeling"),
    ("A computational analysis of the effects of different funding mechanisms on the performance and sustainability of innovation hubs within innovation systems.", "Computational or Modeling"),
    ("Developing a mathematical model to simulate the co-evolution of technological innovation and industry dynamics within innovation systems.", "Computational or Modeling"),
    ("Using machine learning techniques to predict the success and failure of startups within innovation ecosystems in innovation systems.", "Computational or Modeling"),
    ("A simulation study investigating the effects of regulatory environments on the diffusion of disruptive innovations within innovation systems.", "Computational or Modeling"),
    ("Developing a computational framework to analyze the dynamics of knowledge flows and innovation networks within regional innovation systems.", "Computational or Modeling"),
    ("Using network analysis and computational modeling to study the effects of different collaboration patterns on innovation outcomes within innovation systems.", "Computational or Modeling"),
    ("Developing an optimization model to identify the optimal allocation of resources for research and development activities within innovation systems.", "Computational or Modeling"),
    ("A computational analysis of the impact of technology transfer mechanisms on the diffusion of innovations within innovation systems.", "Computational or Modeling"),
    ("Using data mining techniques to uncover patterns and trends in innovation activities within innovation systems.", "Computational or Modeling"),
    ("Developing a simulation model to study the effects of knowledge flows and collaboration dynamics on the resilience of innovation systems.", "Computational or Modeling"),


    # Case Studies
    ("A case study on the successful implementation of a new customer relationship management system.", "Case Study"),
    ("An in-depth analysis of a multinational company's marketing strategies in emerging markets.", "Case Study"),
    ("Examining the impact of a community-based intervention program through a case study in a rural area.", "Case Study"),
    ("A case study on the implementation of lean manufacturing principles in a textile factory.", "Case Study"),
    ("Examining the effectiveness of a community-based health program in reducing childhood obesity: A case study in a rural area.", "Case Study"),
    ("A case study of a successful urban renewal project: The transformation of a deteriorated neighborhood.", "Case Study"),
    ("Investigating the impact of employee training and development programs on organizational performance: A case study of a software company.", "Case Study"),
    ("A case study of the adoption and implementation of renewable energy technologies in a developing country.", "Case Study"),
    ("Analyzing the factors influencing consumer behavior in online shopping: A case study of an e-commerce platform.", "Case Study"),
    ("Examining the social and environmental impacts of a large-scale infrastructure project: A case study of a dam construction.", "Case Study"),
    ("A case study on the management of a multinational corporation during a financial crisis.", "Case Study"),
    ("Investigating the strategies for talent retention in the IT industry: A case study of a technology company.", "Case Study"),
    ("A case study of the effects of corporate social responsibility initiatives on brand reputation.", "Case Study"),
    ("Analyzing the challenges and opportunities of digital transformation in the banking sector: A case study of a national bank.", "Case Study"),
    ("A case study on the implementation of agile project management methodology in software development.", "Case Study"),
    ("A comparative case study of two regional innovation systems to examine the factors influencing their innovation performance and the strategies adopted to overcome challenges.", "Case Study"),
    ("An in-depth analysis of a successful university-industry collaboration initiative within an innovation system, exploring the key drivers and outcomes of the partnership.", "Case Study"),
    ("Investigating the role of intermediaries in facilitating knowledge transfer and collaboration among actors in a regional innovation system through a case study of a technology transfer office.", "Case Study"),
    ("A comparative case study of two innovation ecosystems to identify the factors influencing their success and the strategies adopted for nurturing innovation within the systems.", "Case Study"),
    ("An in-depth analysis of a successful university-industry collaboration initiative within an innovation system, exploring the key drivers and outcomes of the partnership.", "Case Study"),
    ("Investigating the role of knowledge-intensive firms in fostering innovation and knowledge diffusion within innovation systems through a case study approach.", "Case Study"),
    ("A case study of a successful innovation district, analyzing the factors that contribute to its growth and the mechanisms for collaboration and knowledge sharing within the district.", "Case Study"),
    ("Investigating the role of public-private partnerships in fostering innovation and entrepreneurship within innovation systems through a case study of a technology park.", "Case Study"),
    ("A case study of a university spin-off company, examining the factors that led to its success and the strategies it employed to navigate the innovation system.", "Case Study"),
    ("Exploring the dynamics of cross-sector collaboration in a regional innovation system through a case study of a collaborative innovation platform.", "Case Study"),
    ("A case study of a technology incubator, investigating the support mechanisms provided to startups and the impacts on their innovation and growth within the innovation system.", "Case Study"),
    ("Examining the role of regional policies in supporting innovation and entrepreneurship through a case study of a government-led innovation initiative within an innovation system.", "Case Study"),
    ("A case study of a technology transfer office, analyzing its activities and outcomes in facilitating knowledge transfer and commercialization of research within an innovation system.", "Case Study"),
    ("Investigating the factors influencing the success of innovation networks within innovation systems through a case study of a cluster organization.", "Case Study"),
    ("A case study of a successful open innovation project, exploring the mechanisms for collaboration and knowledge exchange within an innovation system.", "Case Study"),
    ("Examining the challenges and opportunities for small and medium-sized enterprises (SMEs) in accessing and participating in innovation networks within innovation systems through a case study approach.", "Case Study"),
    ("A case study of a government-led innovation policy initiative, evaluating its impacts on innovation performance and the development of the innovation system.", "Case Study"),


    # Methodology or Technical Papers
    ("A novel technique for DNA sequencing using nanopore technology.", "Methodology or Technical"),
    ("Development of a new statistical method for analyzing complex survey data.", "Methodology or Technical"),
    ("A protocol for sample preparation in electron microscopy imaging.", "Methodology or Technical"),
    ("A new approach for sentiment analysis using deep learning techniques.", "Methodology or Technical"),
    ("Development of a protocol for the extraction and purification of DNA from ancient remains.", "Methodology or Technical"),
    ("A novel method for identifying unknown compounds using mass spectrometry.", "Methodology or Technical"),
    ("A comparative study of different machine learning algorithms for image classification.", "Methodology or Technical"),
    ("Development of a statistical model for predicting customer churn in the telecommunications industry.", "Methodology or Technical"),
    ("A protocol for the synthesis of gold nanoparticles with controlled size and morphology.", "Methodology or Technical"),
    ("A new technique for enhancing the resolution of optical microscopy in biological imaging.", "Methodology or Technical"),
    ("A methodological framework for conducting qualitative interviews in sociological research.", "Methodology or Technical"),
    ("Development of a software tool for analyzing social media data and detecting trends.", "Methodology or Technical"),
    ("A protocol for the generation and characterization of induced pluripotent stem cells.", "Methodology or Technical"),
    ("A new algorithm for compressing and storing large-scale genomic data.", "Methodology or Technical"),
    ("Development of a protocol for the extraction and analysis of volatile compounds in food samples.", "Methodology or Technical"),
    ("A methodological framework for assessing the innovation capabilities of organizations within innovation systems, integrating qualitative and quantitative indicators.", "Methodology or Technical"),
    ("Developing a novel technique for mapping and visualizing the structure and dynamics of innovation networks within regional innovation systems.", "Methodology or Technical"),
    ("A technical guide to using social network analysis methods for studying knowledge exchange and collaboration patterns in innovation systems.", "Methodology or Technical"),
    ("A methodological framework for assessing the innovation capabilities and performance of organizations within innovation systems.", "Methodology or Technical"),
    ("Developing a novel technique for mapping and analyzing the structure and dynamics of innovation networks within innovation systems.", "Methodology or Technical"),
    ("A technical guide to using social network analysis methods for studying knowledge transfer and collaboration patterns in innovation systems.", "Methodology or Technical"),
    ("Developing a framework for evaluating the innovation readiness and absorptive capacity of organizations within innovation systems.", "Methodology or Technical"),
    ("A technical guide to using machine learning algorithms for predicting innovation trends and identifying emerging technologies within innovation systems.", "Methodology or Technical"),
    ("Proposing a methodological approach for assessing the impact of innovation policies and initiatives on the performance of regional innovation systems.", "Methodology or Technical"),
    ("Developing a novel technique for measuring and benchmarking the innovation performance of firms within innovation systems.", "Methodology or Technical"),
    ("A technical guide to using social media data for studying innovation networks and knowledge exchange within innovation systems.", "Methodology or Technical"),
    ("Introducing a framework for mapping the innovation ecosystem of a specific industry within a regional innovation system.", "Methodology or Technical"),
    ("A methodological approach for evaluating the effectiveness of innovation support programs in fostering entrepreneurship within innovation systems.", "Methodology or Technical"),
    ("Developing a systematic method for identifying and analyzing disruptive technologies within innovation systems.", "Methodology or Technical"),
    ("A technical guide to using patent data for analyzing innovation patterns and trends within innovation systems.", "Methodology or Technical"),
    ("Proposing a methodological framework for assessing the social impact of innovation within regional innovation systems.", "Methodology or Technical"),
    ("A technical guide to using text mining techniques for analyzing innovation-related documents and uncovering knowledge flows within innovation systems.", "Methodology or Technical"),
    ("Developing a framework for evaluating the effectiveness and efficiency of innovation clusters within regional innovation systems.", "Methodology or Technical"),


    # Meta-analyses
    ("A meta-analysis of studies investigating the effectiveness of mindfulness-based interventions for stress reduction.", "Meta-analysis"),
    ("An overview of published trials using a meta-analysis to evaluate the efficacy of a specific medication.", "Meta-analysis"),
    ("Meta-analysis of randomized controlled trials on the effectiveness of physical exercise for depression treatment.", "Meta-analysis"),
    ("A meta-analysis of studies investigating the effectiveness of mindfulness-based interventions for anxiety disorders.", "Meta-analysis"),
    ("An overview of published trials using a meta-analysis to evaluate the efficacy of a specific therapeutic intervention.", "Meta-analysis"),
    ("Meta-analysis of randomized controlled trials on the effectiveness of exercise interventions for weight loss.", "Meta-analysis"),
    ("A systematic review and meta-analysis of studies on the association between dietary factors and cancer risk.", "Meta-analysis"),
    ("A meta-analysis of studies examining the impact of educational interventions on academic achievement.", "Meta-analysis"),
    ("An overview of published trials using a meta-analysis to assess the effectiveness of pharmacological treatments for depression.", "Meta-analysis"),
    ("Meta-analysis of randomized controlled trials on the effects of dietary supplements on athletic performance.", "Meta-analysis"),
    ("A systematic review and meta-analysis of studies on the relationship between sleep duration and cardiovascular health.", "Meta-analysis"),
    ("A meta-analysis of studies investigating the efficacy of cognitive training programs for improving cognitive function in older adults.", "Meta-analysis"),
    ("An overview of published trials using a meta-analysis to evaluate the effectiveness of psychological interventions for post-traumatic stress disorder.", "Meta-analysis"),
    ("Meta-analysis of studies examining the impact of exercise interventions on mental health outcomes in adolescents.", "Meta-analysis"),
    ("A systematic review and meta-analysis of studies on the association between smoking and the risk of developing respiratory diseases.", "Meta-analysis"),
    ("A meta-analysis of studies examining the relationship between government policies and innovation outcomes within innovation systems.", "Meta-analysis"),
    ("An overview and quantitative synthesis of research on the role of knowledge spillovers in driving innovation within innovation systems.", "Meta-analysis"),
    ("A meta-analysis of studies investigating the impact of knowledge-intensive services on innovation performance within innovation systems.", "Meta-analysis"),
    ("A meta-analysis of studies examining the impact of collaborative innovation networks on the performance of firms within innovation systems.", "Meta-analysis"),
    ("An overview and quantitative synthesis of research on the relationship between intellectual property rights and innovation activities within innovation systems.", "Meta-analysis"),
    ("A meta-analysis of studies investigating the factors influencing knowledge spillovers and their effects on innovation within innovation systems.", "Meta-analysis"),
    ("An analysis of meta-analytic findings on the relationship between university-industry collaboration and innovation outcomes within innovation systems.", "Meta-analysis"),
    ("A meta-analysis of studies examining the impact of innovation policy instruments on firm-level innovation performance within national innovation systems.", "Meta-analysis"),
    ("An overview and quantitative synthesis of research on the role of networks and social capital in innovation systems.", "Meta-analysis"),
    ("A meta-analysis of studies investigating the effects of government funding on the innovation capability and performance of firms within innovation systems.", "Meta-analysis"),
    ("An analysis of meta-analytic findings on the relationship between knowledge diversity and innovation outcomes within innovation systems.", "Meta-analysis"),
    ("A meta-analysis of studies examining the impact of venture capital on the growth and innovation performance of startups within innovation systems.", "Meta-analysis"),
    ("An overview and quantitative synthesis of research on the role of universities and research institutions in innovation systems.", "Meta-analysis"),
    ("A meta-analysis of studies investigating the effects of open innovation practices on the innovation performance of firms within innovation systems.", "Meta-analysis"),
    ("An analysis of meta-analytic findings on the relationship between knowledge spillovers and regional innovation systems.", "Meta-analysis"),


    # Short Communications or Brief Reports
    ("A preliminary report on a newly discovered species of deep-sea marine organisms.", "Short Communications or Brief Reports"),
    ("A brief update on recent advancements in gene-editing technologies.", "Short Communications or Brief Reports"),
    ("A short communication on the identification of a novel biomarker for early cancer detection.", "Short Communications or Brief Reports"),
    ("A brief report on the discovery of a new exoplanet using the Kepler telescope.", "Short Communications or Brief Reports"),
    ("A short communication on the efficacy of a newly developed vaccine against a specific virus.", "Short Communications or Brief Reports"),
    ("A preliminary study on the use of virtual reality for pain management in pediatric patients.", "Short Communications or Brief Reports"),
    ("A brief report on the findings of a survey assessing public opinion on climate change.", "Short Communications or Brief Reports"),
    ("A short communication on the development of a smartphone app for monitoring daily physical activity.", "Short Communications or Brief Reports"),
    ("A preliminary report on the impact of COVID-19 on mental health in healthcare workers.", "Short Communications or Brief Reports"),
    ("A brief report on the identification of a potential biomarker for early diagnosis of Alzheimer's disease.", "Short Communications or Brief Reports"),
    ("A short communication on the investigation of the effects of a new drug in a small patient cohort.", "Short Communications or Brief Reports"),
    ("A preliminary report on the association between dietary habits and cardiovascular health in a specific population.", "Short Communications or Brief Reports"),
    ("A brief communication on the development of a low-cost diagnostic tool for detecting infectious diseases.", "Short Communications or Brief Reports"),
    ("A short report on the impact of social media usage on self-esteem and body image in young adults.", "Short Communications or Brief Reports"),
    ("A preliminary study on the effectiveness of an educational intervention in improving financial literacy.", "Short Communications or Brief Reports"),
    ("A brief report on the emerging trends in open innovation practices within innovation systems and their implications for knowledge sharing and collaboration.", "Short Communications or Brief Reports"),
    ("A short communication on the role of incubators and accelerators in supporting entrepreneurship and innovation activities within regional innovation systems.", "Short Communications or Brief Reports"),
    ("An update on the recent advancements in blockchain technology and its potential applications in enhancing transparency and trust in innovation systems.", "Short Communications or Brief Reports"),
    ("A brief report on the challenges and opportunities in integrating sustainability considerations into innovation systems and promoting sustainable innovation.", "Short Communications or Brief Reports"),
    ("A short communication on the role of universities as key actors in fostering knowledge transfer and innovation within innovation systems.", "Short Communications or Brief Reports"),
    ("An update on the latest research findings on the impact of digitalization and Industry 4.0 technologies on innovation processes within innovation systems.", "Short Communications or Brief Reports"),
    ("A brief report on the importance of intellectual property rights protection in stimulating innovation and knowledge creation within innovation systems.", "Short Communications or Brief Reports"),
    ("An update on the recent policy developments and initiatives aimed at promoting innovation and entrepreneurship within national innovation systems.", "Short Communications or Brief Reports"),
    ("A short communication on the role of venture capital funding in supporting high-growth startups and fostering innovation within innovation systems.", "Short Communications or Brief Reports"),
    ("An update on the advancements in artificial intelligence and machine learning techniques and their potential applications in innovation systems research.", "Short Communications or Brief Reports"),
    ("A brief report on the use of social media and online platforms for open innovation and crowdsourcing within innovation systems.", "Short Communications or Brief Reports"),
    ("An update on the latest trends and practices in user-centered innovation and co-creation within innovation systems.", "Short Communications or Brief Reports"),
    ("A short communication on the role of government funding programs in stimulating innovation activities and promoting collaboration within innovation systems.", "Short Communications or Brief Reports"),
    ("An update on the recent developments in the field of technology transfer and commercialization of innovations within innovation systems.", "Short Communications or Brief Reports")
]

# Preprocess the existing abstracts using TextBlob
preprocessed_abstracts = [TextBlob(abstract.lower()).words for abstract, _ in abstracts]

# Create feature vectors using TF-IDF vectorizer
vectorizer = TfidfVectorizer(preprocessor=' '.join)
feature_vectors = vectorizer.fit_transform(preprocessed_abstracts)

# Train the LinearSVC classifier using the existing abstracts
classifier = LinearSVC()
classifier.fit(feature_vectors, [category for _, category in abstracts])

# Read the abstracts from the CSV file
df = pd.read_csv('Abstract_CSV.csv', encoding='latin1')
new_abstracts = df['Abstract'].tolist()

# Preprocess the new abstracts using TextBlob
preprocessed_new_abstracts = [TextBlob(abstract.lower()).words for abstract in new_abstracts]

# Create feature vectors for the new abstracts
new_feature_vectors = vectorizer.transform(preprocessed_new_abstracts)

# Predict categories for the new abstracts
predictions = classifier.predict(new_feature_vectors)

# Create a new DataFrame with the categorized abstracts and DOIs
result_df = pd.DataFrame({'Category': predictions})

# Save the results to a new CSV file
result_df.to_csv('Abstract_Categorized.csv', index=False)